include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const
    - unnecessary_new
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - sort_child_properties_last
    - use_full_hex_values_for_flutter_colors
    - prefer_single_quotes
    - require_trailing_commas

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    invalid_annotation_target: ignore
